### ISSUE TITLE
question about file /data

### ISSUE THREAD

**Issue by DHrobotman** [VIS4ROB-lab/multirotors_landing#1]
Hello, may I ask if your latest updated **/data** file contains the training results you provided? How can I verify that last_ step_ What about model. zip? 
Directly based on

`python3 scripts/quadrotor_ testing.py -w ~/multicopters_ landing/experiments/data/trained_ policy/last_ step_ model.zip`

The following error will occur

```
Traceback (most recent call last):
File "scripts/quadrotor_testing.py", line 91, in <module>
main()
File "scripts/quadrotor_testing.py", line 77, in main
model = PPO2.load(args.weight, env=env if not args.lstm else None)
File "/home/lyh/venvs/landing/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 936, in load
data, params = cls._ load_ from_ file(load_path, custom_objects=custom_objects)
File "/home/lyh/venvs/landing/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 666, in _ load_ from_ file
data = json_ to_ data(json_data, custom_objects=custom_objects)
File "/home/lyh/venvs/landing/lib/python3.6/site-packages/stable_baselines/common/save_util.py", line 120, in json_ to_ data
base64.b64decode(serialization.encode())
ModuleNotFoundError: No module named 'multirotors_ landing_ rl'
WARNING:root:Closing RL environment!
[Vec quad_landing_test] Closing!
```

**Comment by lucaBartolomei** [comment]
Hi,

I just tested the commands on a new installation and everything works fine on my side. 

I think you need to re-install the packages and the virtual environment from scratch, because your installation is still referring to an old version of the code (private one, that you had access to), namely _multicopters_landing_ instead of _multirotors_landing_. The weights expect to find the package _multirotors_landing_rl_, as the error is telling you.

I hope this helps. I will close this issue then. Feel free to re-open it if you need further help.
